// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/aasumitro/goms/internal/bff/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// IStoreGRPCRepository is an autogenerated mock type for the IStoreGRPCRepository type
type IStoreGRPCRepository struct {
	mock.Mock
}

// All provides a mock function with given fields: ctx
func (_m *IStoreGRPCRepository) All(ctx context.Context) ([]*entity.Store, error) {
	ret := _m.Called(ctx)

	var r0 []*entity.Store
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.Store); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Store)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Erase provides a mock function with given fields: ctx, arg
func (_m *IStoreGRPCRepository) Erase(ctx context.Context, arg *entity.Store) error {
	ret := _m.Called(ctx, arg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Store) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: ctx, arg
func (_m *IStoreGRPCRepository) Find(ctx context.Context, arg *entity.Store) (*entity.Store, error) {
	ret := _m.Called(ctx, arg)

	var r0 *entity.Store
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Store) *entity.Store); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Store)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *entity.Store) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Patch provides a mock function with given fields: ctx, arg
func (_m *IStoreGRPCRepository) Patch(ctx context.Context, arg *entity.Store) error {
	ret := _m.Called(ctx, arg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Store) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Record provides a mock function with given fields: ctx, arg
func (_m *IStoreGRPCRepository) Record(ctx context.Context, arg *entity.Store) error {
	ret := _m.Called(ctx, arg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Store) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIStoreGRPCRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewIStoreGRPCRepository creates a new instance of IStoreGRPCRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIStoreGRPCRepository(t mockConstructorTestingTNewIStoreGRPCRepository) *IStoreGRPCRepository {
	mock := &IStoreGRPCRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
