// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/aasumitro/goms/internal/store/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// IStoreRepository is an autogenerated mock type for the IStoreRepository type
type IStoreRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, arg
func (_m *IStoreRepository) Delete(ctx context.Context, arg *entity.Store) error {
	ret := _m.Called(ctx, arg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Store) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Insert provides a mock function with given fields: ctx, args
func (_m *IStoreRepository) Insert(ctx context.Context, args ...*entity.Store) error {
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...*entity.Store) error); ok {
		r0 = rf(ctx, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Select provides a mock function with given fields: ctx, args
func (_m *IStoreRepository) Select(ctx context.Context, args ...string) ([]*entity.Store, error) {
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []*entity.Store
	if rf, ok := ret.Get(0).(func(context.Context, ...string) []*entity.Store); ok {
		r0 = rf(ctx, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Store)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = rf(ctx, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, arg
func (_m *IStoreRepository) Update(ctx context.Context, arg *entity.Store) error {
	ret := _m.Called(ctx, arg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Store) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIStoreRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewIStoreRepository creates a new instance of IStoreRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIStoreRepository(t mockConstructorTestingTNewIStoreRepository) *IStoreRepository {
	mock := &IStoreRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
