// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/aasumitro/goms/internal/store/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// IStoreService is an autogenerated mock type for the IStoreService type
type IStoreService struct {
	mock.Mock
}

// All provides a mock function with given fields: ctx
func (_m *IStoreService) All(ctx context.Context) ([]*entity.Store, error) {
	ret := _m.Called(ctx)

	var r0 []*entity.Store
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.Store); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Store)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Erase provides a mock function with given fields: ctx, arg
func (_m *IStoreService) Erase(ctx context.Context, arg *entity.Store) error {
	ret := _m.Called(ctx, arg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Store) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: ctx, arg
func (_m *IStoreService) Find(ctx context.Context, arg *entity.Store) (*entity.Store, error) {
	ret := _m.Called(ctx, arg)

	var r0 *entity.Store
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Store) *entity.Store); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Store)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *entity.Store) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Patch provides a mock function with given fields: ctx, arg
func (_m *IStoreService) Patch(ctx context.Context, arg *entity.Store) error {
	ret := _m.Called(ctx, arg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Store) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Record provides a mock function with given fields: ctx, args
func (_m *IStoreService) Record(ctx context.Context, args ...*entity.Store) error {
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...*entity.Store) error); ok {
		r0 = rf(ctx, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIStoreService interface {
	mock.TestingT
	Cleanup(func())
}

// NewIStoreService creates a new instance of IStoreService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIStoreService(t mockConstructorTestingTNewIStoreService) *IStoreService {
	mock := &IStoreService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
