// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeStoreGRPCHandlerServer is an autogenerated mock type for the UnsafeStoreGRPCHandlerServer type
type UnsafeStoreGRPCHandlerServer struct {
	mock.Mock
}

// mustEmbedUnimplementedStoreGRPCHandlerServer provides a mock function with given fields:
func (_m *UnsafeStoreGRPCHandlerServer) mustEmbedUnimplementedStoreGRPCHandlerServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafeStoreGRPCHandlerServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeStoreGRPCHandlerServer creates a new instance of UnsafeStoreGRPCHandlerServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeStoreGRPCHandlerServer(t mockConstructorTestingTNewUnsafeStoreGRPCHandlerServer) *UnsafeStoreGRPCHandlerServer {
	mock := &UnsafeStoreGRPCHandlerServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
