// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: pkg/pb/book.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionType int32

const (
	ActionType_SPECIFIED ActionType = 0
	ActionType_RELATED   ActionType = 1
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "SPECIFIED",
		1: "RELATED",
	}
	ActionType_value = map[string]int32{
		"SPECIFIED": 0,
		"RELATED":   1,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_pb_book_proto_enumTypes[0].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_pkg_pb_book_proto_enumTypes[0]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_pb_book_proto_rawDescGZIP(), []int{0}
}

// The request message containing the user's name.
type BookModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StoreId uint32 `protobuf:"varint,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *BookModel) Reset() {
	*x = BookModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_book_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookModel) ProtoMessage() {}

func (x *BookModel) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_book_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookModel.ProtoReflect.Descriptor instead.
func (*BookModel) Descriptor() ([]byte, []int) {
	return file_pkg_pb_book_proto_rawDescGZIP(), []int{0}
}

func (x *BookModel) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BookModel) GetStoreId() uint32 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *BookModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BookIDModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type ActionType `protobuf:"varint,2,opt,name=type,proto3,enum=proto.ActionType" json:"type,omitempty"`
}

func (x *BookIDModel) Reset() {
	*x = BookIDModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_book_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookIDModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookIDModel) ProtoMessage() {}

func (x *BookIDModel) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_book_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookIDModel.ProtoReflect.Descriptor instead.
func (*BookIDModel) Descriptor() ([]byte, []int) {
	return file_pkg_pb_book_proto_rawDescGZIP(), []int{1}
}

func (x *BookIDModel) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BookIDModel) GetType() ActionType {
	if x != nil {
		return x.Type
	}
	return ActionType_SPECIFIED
}

type BookAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoreId uint32 `protobuf:"varint,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *BookAddRequest) Reset() {
	*x = BookAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_book_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookAddRequest) ProtoMessage() {}

func (x *BookAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_book_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookAddRequest.ProtoReflect.Descriptor instead.
func (*BookAddRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_book_proto_rawDescGZIP(), []int{2}
}

func (x *BookAddRequest) GetStoreId() uint32 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *BookAddRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BookRowsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Books []*BookModel `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
}

func (x *BookRowsResponse) Reset() {
	*x = BookRowsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_book_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookRowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookRowsResponse) ProtoMessage() {}

func (x *BookRowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_book_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookRowsResponse.ProtoReflect.Descriptor instead.
func (*BookRowsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_book_proto_rawDescGZIP(), []int{3}
}

func (x *BookRowsResponse) GetBooks() []*BookModel {
	if x != nil {
		return x.Books
	}
	return nil
}

type BookRowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book *BookModel `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
}

func (x *BookRowResponse) Reset() {
	*x = BookRowResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_book_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookRowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookRowResponse) ProtoMessage() {}

func (x *BookRowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_book_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookRowResponse.ProtoReflect.Descriptor instead.
func (*BookRowResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_book_proto_rawDescGZIP(), []int{4}
}

func (x *BookRowResponse) GetBook() *BookModel {
	if x != nil {
		return x.Book
	}
	return nil
}

type BookBoolResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *BookBoolResponse) Reset() {
	*x = BookBoolResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_book_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookBoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookBoolResponse) ProtoMessage() {}

func (x *BookBoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_book_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookBoolResponse.ProtoReflect.Descriptor instead.
func (*BookBoolResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_book_proto_rawDescGZIP(), []int{5}
}

func (x *BookBoolResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_pkg_pb_book_proto protoreflect.FileDescriptor

var file_pkg_pb_book_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a, 0x0a, 0x09, 0x42, 0x6f,
	0x6f, 0x6b, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x44, 0x0a, 0x0b, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x44,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x3f, 0x0a, 0x0e,
	0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x0a,
	0x10, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x6f, 0x77, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x26, 0x0a, 0x05, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x52, 0x05, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x22, 0x37, 0x0a, 0x0f, 0x42, 0x6f, 0x6f,
	0x6b, 0x52, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x04,
	0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x04, 0x62, 0x6f,
	0x6f, 0x6b, 0x22, 0x2a, 0x0a, 0x10, 0x42, 0x6f, 0x6f, 0x6b, 0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x28,
	0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52,
	0x45, 0x4c, 0x41, 0x54, 0x45, 0x44, 0x10, 0x01, 0x32, 0xab, 0x02, 0x0a, 0x0f, 0x42, 0x6f, 0x6f,
	0x6b, 0x47, 0x52, 0x50, 0x43, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x05,
	0x46, 0x65, 0x74, 0x63, 0x68, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f,
	0x6f, 0x6b, 0x49, 0x44, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x6f, 0x77, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x04, 0x53, 0x68, 0x6f, 0x77, 0x12, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x44, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x6f, 0x77,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x05, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x6f, 0x6b,
	0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x42, 0x6f,
	0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x07,
	0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x44, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x1a, 0x17, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_pb_book_proto_rawDescOnce sync.Once
	file_pkg_pb_book_proto_rawDescData = file_pkg_pb_book_proto_rawDesc
)

func file_pkg_pb_book_proto_rawDescGZIP() []byte {
	file_pkg_pb_book_proto_rawDescOnce.Do(func() {
		file_pkg_pb_book_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_book_proto_rawDescData)
	})
	return file_pkg_pb_book_proto_rawDescData
}

var file_pkg_pb_book_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_pb_book_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_pb_book_proto_goTypes = []interface{}{
	(ActionType)(0),          // 0: proto.ActionType
	(*BookModel)(nil),        // 1: proto.BookModel
	(*BookIDModel)(nil),      // 2: proto.BookIDModel
	(*BookAddRequest)(nil),   // 3: proto.BookAddRequest
	(*BookRowsResponse)(nil), // 4: proto.BookRowsResponse
	(*BookRowResponse)(nil),  // 5: proto.BookRowResponse
	(*BookBoolResponse)(nil), // 6: proto.BookBoolResponse
}
var file_pkg_pb_book_proto_depIdxs = []int32{
	0, // 0: proto.BookIDModel.type:type_name -> proto.ActionType
	1, // 1: proto.BookRowsResponse.books:type_name -> proto.BookModel
	1, // 2: proto.BookRowResponse.book:type_name -> proto.BookModel
	2, // 3: proto.BookGRPCHandler.Fetch:input_type -> proto.BookIDModel
	2, // 4: proto.BookGRPCHandler.Show:input_type -> proto.BookIDModel
	3, // 5: proto.BookGRPCHandler.Store:input_type -> proto.BookAddRequest
	1, // 6: proto.BookGRPCHandler.Update:input_type -> proto.BookModel
	2, // 7: proto.BookGRPCHandler.Destroy:input_type -> proto.BookIDModel
	4, // 8: proto.BookGRPCHandler.Fetch:output_type -> proto.BookRowsResponse
	5, // 9: proto.BookGRPCHandler.Show:output_type -> proto.BookRowResponse
	6, // 10: proto.BookGRPCHandler.Store:output_type -> proto.BookBoolResponse
	6, // 11: proto.BookGRPCHandler.Update:output_type -> proto.BookBoolResponse
	6, // 12: proto.BookGRPCHandler.Destroy:output_type -> proto.BookBoolResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_pb_book_proto_init() }
func file_pkg_pb_book_proto_init() {
	if File_pkg_pb_book_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_book_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_book_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookIDModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_book_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_book_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookRowsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_book_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookRowResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_book_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookBoolResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_book_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_book_proto_goTypes,
		DependencyIndexes: file_pkg_pb_book_proto_depIdxs,
		EnumInfos:         file_pkg_pb_book_proto_enumTypes,
		MessageInfos:      file_pkg_pb_book_proto_msgTypes,
	}.Build()
	File_pkg_pb_book_proto = out.File
	file_pkg_pb_book_proto_rawDesc = nil
	file_pkg_pb_book_proto_goTypes = nil
	file_pkg_pb_book_proto_depIdxs = nil
}
