// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: pkg/pb/store.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *StoreModel) Reset() {
	*x = StoreModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_store_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreModel) ProtoMessage() {}

func (x *StoreModel) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_store_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreModel.ProtoReflect.Descriptor instead.
func (*StoreModel) Descriptor() ([]byte, []int) {
	return file_pkg_pb_store_proto_rawDescGZIP(), []int{0}
}

func (x *StoreModel) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StoreModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StoreIDModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StoreIDModel) Reset() {
	*x = StoreIDModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_store_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreIDModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreIDModel) ProtoMessage() {}

func (x *StoreIDModel) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_store_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreIDModel.ProtoReflect.Descriptor instead.
func (*StoreIDModel) Descriptor() ([]byte, []int) {
	return file_pkg_pb_store_proto_rawDescGZIP(), []int{1}
}

func (x *StoreIDModel) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StoreNameModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *StoreNameModel) Reset() {
	*x = StoreNameModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_store_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreNameModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreNameModel) ProtoMessage() {}

func (x *StoreNameModel) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_store_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreNameModel.ProtoReflect.Descriptor instead.
func (*StoreNameModel) Descriptor() ([]byte, []int) {
	return file_pkg_pb_store_proto_rawDescGZIP(), []int{2}
}

func (x *StoreNameModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StoreEmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StoreEmptyRequest) Reset() {
	*x = StoreEmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_store_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreEmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreEmptyRequest) ProtoMessage() {}

func (x *StoreEmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_store_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreEmptyRequest.ProtoReflect.Descriptor instead.
func (*StoreEmptyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_store_proto_rawDescGZIP(), []int{3}
}

type StoreRowsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stores []*StoreModel `protobuf:"bytes,1,rep,name=stores,proto3" json:"stores,omitempty"`
}

func (x *StoreRowsResponse) Reset() {
	*x = StoreRowsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_store_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreRowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRowsResponse) ProtoMessage() {}

func (x *StoreRowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_store_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRowsResponse.ProtoReflect.Descriptor instead.
func (*StoreRowsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_store_proto_rawDescGZIP(), []int{4}
}

func (x *StoreRowsResponse) GetStores() []*StoreModel {
	if x != nil {
		return x.Stores
	}
	return nil
}

type StoreRowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Store *StoreModel `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
}

func (x *StoreRowResponse) Reset() {
	*x = StoreRowResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_store_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreRowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRowResponse) ProtoMessage() {}

func (x *StoreRowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_store_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRowResponse.ProtoReflect.Descriptor instead.
func (*StoreRowResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_store_proto_rawDescGZIP(), []int{5}
}

func (x *StoreRowResponse) GetStore() *StoreModel {
	if x != nil {
		return x.Store
	}
	return nil
}

type StoreBoolResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *StoreBoolResponse) Reset() {
	*x = StoreBoolResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_store_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreBoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreBoolResponse) ProtoMessage() {}

func (x *StoreBoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_store_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreBoolResponse.ProtoReflect.Descriptor instead.
func (*StoreBoolResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_store_proto_rawDescGZIP(), []int{6}
}

func (x *StoreBoolResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_pkg_pb_store_proto protoreflect.FileDescriptor

var file_pkg_pb_store_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x0a, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1e, 0x0a,
	0x0c, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x44, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x24, 0x0a,
	0x0e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3e, 0x0a, 0x11, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x52, 0x6f, 0x77, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a,
	0x06, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x52, 0x06, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x22, 0x3b, 0x0a, 0x10, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x52, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x05,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x05,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x22, 0x2b, 0x0a, 0x11, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x42, 0x6f,
	0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x32, 0xba, 0x02, 0x0a, 0x10, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x47, 0x52, 0x50, 0x43,
	0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x3d, 0x0a, 0x05, 0x46, 0x65, 0x74, 0x63, 0x68,
	0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x6f, 0x77, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x04, 0x53, 0x68, 0x6f, 0x77, 0x12, 0x13,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x44, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x52, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a,
	0x0a, 0x05, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x1a, 0x18,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x42, 0x6f, 0x6f, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x06, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x07, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x12, 0x13,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x44, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pkg_pb_store_proto_rawDescOnce sync.Once
	file_pkg_pb_store_proto_rawDescData = file_pkg_pb_store_proto_rawDesc
)

func file_pkg_pb_store_proto_rawDescGZIP() []byte {
	file_pkg_pb_store_proto_rawDescOnce.Do(func() {
		file_pkg_pb_store_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_store_proto_rawDescData)
	})
	return file_pkg_pb_store_proto_rawDescData
}

var file_pkg_pb_store_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_pb_store_proto_goTypes = []interface{}{
	(*StoreModel)(nil),        // 0: proto.StoreModel
	(*StoreIDModel)(nil),      // 1: proto.StoreIDModel
	(*StoreNameModel)(nil),    // 2: proto.StoreNameModel
	(*StoreEmptyRequest)(nil), // 3: proto.StoreEmptyRequest
	(*StoreRowsResponse)(nil), // 4: proto.StoreRowsResponse
	(*StoreRowResponse)(nil),  // 5: proto.StoreRowResponse
	(*StoreBoolResponse)(nil), // 6: proto.StoreBoolResponse
}
var file_pkg_pb_store_proto_depIdxs = []int32{
	0, // 0: proto.StoreRowsResponse.stores:type_name -> proto.StoreModel
	0, // 1: proto.StoreRowResponse.store:type_name -> proto.StoreModel
	3, // 2: proto.StoreGRPCHandler.Fetch:input_type -> proto.StoreEmptyRequest
	1, // 3: proto.StoreGRPCHandler.Show:input_type -> proto.StoreIDModel
	2, // 4: proto.StoreGRPCHandler.Store:input_type -> proto.StoreNameModel
	0, // 5: proto.StoreGRPCHandler.Update:input_type -> proto.StoreModel
	1, // 6: proto.StoreGRPCHandler.Destroy:input_type -> proto.StoreIDModel
	4, // 7: proto.StoreGRPCHandler.Fetch:output_type -> proto.StoreRowsResponse
	5, // 8: proto.StoreGRPCHandler.Show:output_type -> proto.StoreRowResponse
	6, // 9: proto.StoreGRPCHandler.Store:output_type -> proto.StoreBoolResponse
	6, // 10: proto.StoreGRPCHandler.Update:output_type -> proto.StoreBoolResponse
	6, // 11: proto.StoreGRPCHandler.Destroy:output_type -> proto.StoreBoolResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_pb_store_proto_init() }
func file_pkg_pb_store_proto_init() {
	if File_pkg_pb_store_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_store_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_store_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreIDModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_store_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreNameModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_store_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreEmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_store_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreRowsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_store_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreRowResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_store_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreBoolResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_store_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_store_proto_goTypes,
		DependencyIndexes: file_pkg_pb_store_proto_depIdxs,
		MessageInfos:      file_pkg_pb_store_proto_msgTypes,
	}.Build()
	File_pkg_pb_store_proto = out.File
	file_pkg_pb_store_proto_rawDesc = nil
	file_pkg_pb_store_proto_goTypes = nil
	file_pkg_pb_store_proto_depIdxs = nil
}
